#!/usr/bin/env python3
"""
Helper script to set up Exact Online OAuth authentication.

This script helps you:
1. Generate the authorization URL to start the OAuth flow
2. Exchange the authorization code for tokens
3. Save credentials to .env.exact

Prerequisites:
- Exact Online trial account (Exact voor Boekhouden)
- App registered at https://apps.exactonline.com
- ngrok running (for callback URL)

Usage:
    # Step 1: Generate auth URL
    uv run python scripts/setup_exact_oauth.py --generate-url
    
    # Step 2: After authorizing and getting code, exchange for tokens
    uv run python scripts/setup_exact_oauth.py --exchange-code YOUR_CODE
"""

from __future__ import annotations

import argparse
import sys
import urllib.parse
import webbrowser
from pathlib import Path

import httpx

EXACT_AUTH_URL = "https://start.exactonline.be/api/oauth2/auth"
EXACT_TOKEN_URL = "https://start.exactonline.be/api/oauth2/token"


def generate_auth_url(client_id: str, redirect_uri: str) -> str:
    """Generate the Exact Online authorization URL."""
    params = {
        "client_id": client_id,
        "redirect_uri": redirect_uri,
        "response_type": "code",
        "scope": "openid email offline_access ExactOnlineAPI",
        "force_login": "0",
    }
    return f"{EXACT_AUTH_URL}?{urllib.parse.urlencode(params)}"


def exchange_code_for_tokens(
    client_id: str,
    client_secret: str,
    redirect_uri: str,
    code: str,
) -> dict | None:
    """Exchange authorization code for access and refresh tokens."""
    response = httpx.post(
        EXACT_TOKEN_URL,
        data={
            "grant_type": "authorization_code",
            "client_id": client_id,
            "client_secret": client_secret,
            "code": code,
            "redirect_uri": redirect_uri,
        },
        timeout=30.0,
    )
    
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error exchanging code: {response.status_code}")
        print(response.text)
        return None


def update_env_file(tokens: dict, client_id: str, client_secret: str, redirect_uri: str) -> None:
    """Update the .env.exact file with new tokens."""
    env_path = Path(__file__).resolve().parents[1] / ".env.exact"
    
    env_content = f"""# Exact Online API Configuration
# Generated by setup_exact_oauth.py on {__import__('datetime').datetime.now().isoformat()}

EXACT_CLIENT_ID={client_id}
EXACT_CLIENT_SECRET={client_secret}
EXACT_REFRESH_TOKEN={tokens.get('refresh_token', '')}
EXACT_REDIRECT_URI={redirect_uri}
EXACT_BASE_URL=https://start.exactonline.be

# Division will be auto-discovered
"""
    
    env_path.write_text(env_content)
    print(f"✅ Credentials saved to {env_path}")
    print()
    print("You can now run:")
    print("  uv run python scripts/sync_exact_to_postgres.py --full")


def print_setup_instructions() -> None:
    """Print step-by-step setup instructions."""
    print("=" * 70)
    print("Exact Online OAuth Setup Instructions")
    print("=" * 70)
    print()
    print("Step 1: Get Exact Online Trial")
    print("  - Go to https://www.exact.com/be/nl/try")
    print("  - Sign up for 'Exact voor Boekhouden' (30-day free trial)")
    print()
    print("Step 2: Register Your App")
    print("  - Go to https://apps.exactonline.com")
    print("  - Click 'Register new app'")
    print("  - App name: 'CDP Integration' (or whatever you prefer)")
    print("  - Redirect URI: Your ngrok URL + /callback/exact")
    print("    (e.g., https://abc123.ngrok.io/callback/exact)")
    print("  - Save the Client ID and Client Secret")
    print()
    print("Step 3: Start ngrok")
    print("  - Run: ngrok http 8000")
    print("  - Copy the https URL (e.g., https://abc123.ngrok.io)")
    print()
    print("Step 4: Generate Auth URL")
    print("  - Run: uv run python scripts/setup_exact_oauth.py --generate-url")
    print("  - Or manually build the URL (see docs)")
    print()
    print("Step 5: Authorize")
    print("  - Open the auth URL in your browser")
    print("  - Log in with your Exact trial credentials")
    print("  - Authorize the app")
    print("  - You'll be redirected to ngrok (may show error, that's OK)")
    print("  - Copy the 'code' parameter from the URL")
    print()
    print("Step 6: Exchange Code for Tokens")
    print("  - Run: uv run python scripts/setup_exact_oauth.py --exchange-code YOUR_CODE")
    print()
    print("Step 7: Test Sync")
    print("  - Run: uv run python scripts/sync_exact_to_postgres.py --full")
    print()


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Set up Exact Online OAuth authentication"
    )
    parser.add_argument(
        "--instructions",
        action="store_true",
        help="Print detailed setup instructions",
    )
    parser.add_argument(
        "--generate-url",
        action="store_true",
        help="Generate authorization URL",
    )
    parser.add_argument(
        "--exchange-code",
        type=str,
        metavar="CODE",
        help="Exchange authorization code for tokens",
    )
    parser.add_argument(
        "--client-id",
        type=str,
        help="Exact Online client ID",
    )
    parser.add_argument(
        "--client-secret",
        type=str,
        help="Exact Online client secret",
    )
    parser.add_argument(
        "--redirect-uri",
        type=str,
        help="Redirect URI (your ngrok URL + /callback/exact)",
    )
    
    args = parser.parse_args()
    
    if args.instructions or len(sys.argv) == 1:
        print_setup_instructions()
        return 0
    
    if args.generate_url:
        if not args.client_id or not args.redirect_uri:
            print("Error: --client-id and --redirect-uri are required")
            print()
            print("Example:")
            print("  uv run python scripts/setup_exact_oauth.py --generate-url \\")
            print("    --client-id YOUR_CLIENT_ID \\")
            print("    --redirect-uri https://abc123.ngrok.io/callback/exact")
            return 1
        
        auth_url = generate_auth_url(args.client_id, args.redirect_uri)
        print()
        print("Open this URL in your browser to authorize:")
        print()
        print(auth_url)
        print()
        
        # Try to open browser automatically
        try:
            webbrowser.open(auth_url)
            print("(Browser opened automatically)")
        except Exception:
            pass
        
        print()
        print("After authorizing, copy the 'code' from the redirect URL")
        print("and run:")
        print(f"  uv run python scripts/setup_exact_oauth.py --exchange-code CODE \\")
        print(f"    --client-id {args.client_id} \\")
        print(f"    --client-secret YOUR_SECRET \\")
        print(f"    --redirect-uri {args.redirect_uri}")
        return 0
    
    if args.exchange_code:
        if not args.client_id or not args.client_secret or not args.redirect_uri:
            print("Error: --client-id, --client-secret, and --redirect-uri are required")
            return 1
        
        print(f"Exchanging code for tokens...")
        tokens = exchange_code_for_tokens(
            args.client_id,
            args.client_secret,
            args.redirect_uri,
            args.exchange_code,
        )
        
        if tokens:
            print("✅ Successfully obtained tokens!")
            print()
            print(f"Access token: {tokens.get('access_token', '')[:20]}...")
            print(f"Refresh token: {tokens.get('refresh_token', '')[:20]}...")
            print()
            
            # Save to .env.exact
            update_env_file(tokens, args.client_id, args.client_secret, args.redirect_uri)
            return 0
        else:
            print("❌ Failed to exchange code for tokens")
            return 1
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
